### PR TITLE
Gradle build

### PR DESCRIPTION
**Pull request by evanp**
I was able to open this project in Android Studio just fine. Gradle built it, and I was able to launch it in the emulator. 

I'd love to see this pulled so we can get to work converting to the new Dropbox API.

### CODE REVIEW

**Comment by evanp** [comment]
@dae3 I created a pull request for this branch. Can you come in here to answer any questions people have?

**Comment by evanp** [comment]
@dae3 one question I have is why are there multiple components for pull-to-refresh? Are we using both? Can we get rid of one or both?

screenshot from 2018-03-13 16-48-56

**Comment by dae3** [comment]
@evanp you're right there's no need for multiple components for pull-to-refresh. The whole Gradle project needs cleaning up. I wanted to get it out there to see if there's any interest.

**Comment by evanp** [comment]
@dae3 can you remove one or the other? I'm not sure which is better.

**Comment by evanp** [comment]
@dae3 I can live with them there, btw.

Question: what about the tests? They're still in the tree but I don't see them in the project.

**Comment by dae3** [comment]
@evanp I'll do some more work over the weekend, hopefully get the build cleaned up completely. Do you want to merge now so I can work on this repo or wait until I get my fork cleaned up?

**Comment by evanp** [comment]
OK, I merged this. I'm going to add some new issues for outstanding problems.

**Pull request merged**
